name: Publish to GitHub Pages

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Lektor build
        run: |
            ls -l
            pwd
            sudo apt update
            sudo apt install python3-venv pipx
            pipx ensurepath
            pipx install lektor
            lektor build -O ./dist

      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: dist
          branch: master
          token: ${{ secrets.ACCESS_TOKEN }}